# Homebrew formula for DevCade 1.0.0-rc.4.
#
# Generated by tools/release from packaging/homebrew/devcade.rb.tmpl and the
# release's SHA256SUMS. Do not edit by hand; regenerate it instead.
# Published in the tap repository (cagridursun/homebrew-devcade), used as:
#   brew install cagridursun/devcade/devcade
class Devcade < Formula
  desc "Arcade games that run in your terminal"
  homepage "https://github.com/cagridursun/devcade"
  version "1.0.0-rc.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.4/devcade_1.0.0-rc.4_darwin_arm64.tar.gz"
      sha256 "e0cdb1630410dfe2d59868861f4c4f576ce3a14af20561b8e2156d6609313dc0"
    end
    on_intel do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.4/devcade_1.0.0-rc.4_darwin_amd64.tar.gz"
      sha256 "2f9876aeaf98244609e72136640253e90db8bb524921267c1a195789fa0a98dc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.4/devcade_1.0.0-rc.4_linux_arm64.tar.gz"
      sha256 "0135a76e75c31a6578c97ce707d146a5503fa50387b8dcbfc33aa5dff10ca861"
    end
    on_intel do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.4/devcade_1.0.0-rc.4_linux_amd64.tar.gz"
      sha256 "ac88fb15d5db1b63268d8833b3d16765a2f095cc040d37fcc21c29f794e35348"
    end
  end

  def install
    bin.install "devcade"
    pkgshare.install "LICENSE-NOTICE.txt", "README.md"
  end

  test do
    assert_equal "devcade #{version}", shell_output("#{bin}/devcade --version").strip
    assert_match "snake", shell_output("#{bin}/devcade list")
  end
end
