# Homebrew formula for DevCade 1.0.0-rc.5.
#
# Generated by tools/release from packaging/homebrew/devcade.rb.tmpl and the
# release's SHA256SUMS. Do not edit by hand; regenerate it instead.
# Published in the tap repository (cagridursun/homebrew-devcade), used as:
#   brew install cagridursun/devcade/devcade
class Devcade < Formula
  desc "Arcade games that run in your terminal"
  homepage "https://github.com/cagridursun/devcade"
  version "1.0.0-rc.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.5/devcade_1.0.0-rc.5_darwin_arm64.tar.gz"
      sha256 "632536b84f214a26e55934a8d008f1b9107302e79f74087cded90c7254256160"
    end
    on_intel do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.5/devcade_1.0.0-rc.5_darwin_amd64.tar.gz"
      sha256 "7b192e09d92582dbec58202d141cab9459b6db8744cabe6c5ec2dc8327298ac1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.5/devcade_1.0.0-rc.5_linux_arm64.tar.gz"
      sha256 "15b489747400777002b979854d1f1e3e5f61a8022921fb89e921d08e0c1a4785"
    end
    on_intel do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.5/devcade_1.0.0-rc.5_linux_amd64.tar.gz"
      sha256 "959afc6911a336eba8204e32415bd4d6152ec716dd038858ac9f43e411cb3dbd"
    end
  end

  def install
    bin.install "devcade"
    pkgshare.install "LICENSE-NOTICE.txt", "README.md"
  end

  test do
    assert_equal "devcade #{version}", shell_output("#{bin}/devcade --version").strip
    assert_match "snake", shell_output("#{bin}/devcade list")
  end
end
