# Homebrew formula for DevCade 1.0.0-rc.1.
#
# Generated by tools/release from packaging/homebrew/devcade.rb.tmpl and the
# release's SHA256SUMS. Do not edit by hand; regenerate it instead.
# Published in the tap repository (cagridursun/homebrew-devcade), used as:
#   brew install cagridursun/devcade/devcade
class Devcade < Formula
  desc "Arcade games that run in your terminal"
  homepage "https://github.com/cagridursun/devcade"
  version "1.0.0-rc.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.1/devcade_1.0.0-rc.1_darwin_arm64.tar.gz"
      sha256 "eccc7f81a4ba2cd4ccee2ceb3b023ad9eebdf3ceb538b898f0f5b199578f0252"
    end
    on_intel do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.1/devcade_1.0.0-rc.1_darwin_amd64.tar.gz"
      sha256 "713421dcd6f765c1f0945e6f2d6ef4eb64ffd11158a07f59dd994331cdd1024a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.1/devcade_1.0.0-rc.1_linux_arm64.tar.gz"
      sha256 "fbedaf7221a125f06f398967f3ba8c78bcb31071efd287e01cc1a95611dd9d34"
    end
    on_intel do
      url "https://github.com/cagridursun/devcade/releases/download/v1.0.0-rc.1/devcade_1.0.0-rc.1_linux_amd64.tar.gz"
      sha256 "fe312dab845d497e578629706aadfd74e5a3c8f6f99e9761befb3cf49b6d9296"
    end
  end

  def install
    bin.install "devcade"
    pkgshare.install "LICENSE-NOTICE.txt", "README.md"
  end

  test do
    assert_equal "devcade #{version}", shell_output("#{bin}/devcade --version").strip
    assert_match "snake", shell_output("#{bin}/devcade list")
  end
end
